spring:
  config:
    activate:
      on-profile: local
  application:
    name: monari-back
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  api:
    base-url: http://openAPI.seoul.go.kr:8088
    key: ${SEOUL_API_KEY}
    service-name: ListPublicReservationInstitution
    data-type: json

location:
  init: true


oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: http://localhost:3000/auth/kakao/callback
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:3000/auth/google/callback
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo


jwt:
  secret-key: ${JWT_SECRET_KEY}
  accessToken-expiration-millis: 1800000
